- tests/test_experiments.py
I did this to help me understand the tests -- originally I thought I was going to address #16 in part by adding rows to _generate_data, but then decided against. I don't have strong feelings about whether this is a better way to write the tests or not. I thought it might be a little clearer but maybe that's just because rewriting them forced me to understand them. If you don't prefer this then let's not bother changing it.
> Make the tests a little more concise?

- setup.py
- src/mozanalysis/udf.py
- tests/test_udf.py
> Add some UDFs

- src/mozanalysis/experiment.py
- tests/test_experiment.py
If you start with a DataFrame, aggregate over it, then join from the aggregation to the original DataFrame, then Spark can raise an AnalysisException, complaining about duplicated names even if you've been careful to rename them. Specifically, this happened with 'submission_date_s3'.
Since it _actually is a unique name_, we can use `F.col('submission_date_s3')` instead of `data_source.submission_date_s3` to work around this problem. If someone supplies an `enrollments` table that _does_ have a `submission_date_s3` column then Spark justifiably raises a meaningful error.
Added the fix, a short comment explaining it with a reference to the bug[1], and a test that failed before the bug was fixed.
[1] https://issues.apache.org/jira/browse/SPARK-10925
> Work around bug in Spark joining.

- setup.py
- src/mozanalysis/experiment.py
- tests/test_experiment.py
Use attrs for the experiment class.
This gives us more robust immutability, a free repr, and avoids some
boilerplate.
> Use attrs for Experiment

- setup.py
- src/mozanalysis/experiment.py
- src/mozanalysis/utils.py
- tests/test_experiment.py
- tests/test_utils.py
This is a meaty one. I called out a few key design questions in commit messages along the way. Have a ponder and it's probably worth setting up a meeting for any major discussions. I'd be happy if this went through multiple stages of review (e.g. are we happy with the overall design, then are we happy with the types and type signatures, then are we happy with the code and documentation) but maybe I should leave that up to the reviewer(s)?
> Add time series

- src/mozanalysis/metrics/__init__.py
- src/mozanalysis/metrics/desktop.py
... and a histogram-mean aggregation helper.
> Add main and crash ping data sources

- src/mozanalysis/experiment.py
- tests/test_experiment.py
Fix the date referenced in the TimeLimits single_analysis_window constructor if we aren't collecting data long enough.
> Fix an error message

- setup.cfg
- src/mozanalysis/segments/desktop.py
Render the codebase flake8 3.8.1 compatible.
> Respond to linter changes

- src/mozanalysis/bayesian_stats/__init__.py
Silences a DeprecationWarning that the default dtype will change.
> Initialize Series with explicit dtype

- src/mozanalysis/experiment.py
- src/mozanalysis/metrics/__init__.py
Closes https://github.com/mozilla/mozanalysis/issues/88
There is also `udf.json_extract_histogram` in use, but it'll need to be added to `mozfun` first.
> Use mozfun UDFs

- src/mozanalysis/experiment.py
So give a nicer error message. Fixes #74.
> num_dates_enrollment must be positive

- src/mozanalysis/segments/__init__.py
- src/mozanalysis/segments/desktop.py
- tests/__init__.py
- tests/test_metric_libraries.py
- tests/test_segment_libraries.py
Is there a good place to link people for more context on the segments? I was working from DTMO, which seemed kinda sparse.
> Add friendly names and descriptions for segments

- src/mozanalysis/metrics/desktop.py
@kirill-demtchouk has applied these to an experiment; I wrote them but haven't personally vetted them.
> Add metrics for pocket tile clicks

- src/mozanalysis/bq.py
- src/mozanalysis/experiment.py
- src/mozanalysis/metrics/desktop.py
- tests/test_experiment.py
This is an exploration for fixing https://github.com/mozilla/jetstream/issues/357
I shouldn't have run black on the files I changed...
I haven't tested this yet, just wanted to check if this approach is acceptable.
> Rewrite metrics and enrollments query

- src/mozanalysis/experiment.py
Related to https://github.com/mozilla/jetstream/issues/455
This moves joining enrollments with the analysis windows ends and starts to `build_metrics_query`. This will allow to cache and re-use enrollments tables in jetstream.
> Make enrollments tables independent of analysis windows

- docs/guide.rst
- src/mozanalysis/experiment.py
- tests/test_experiment.py
Required for https://github.com/mozilla/jetstream/issues/561
> Add monthly time series period

- src/mozanalysis/experiment.py
- src/mozanalysis/metrics/firefox_ios.py
- tests/test_experiment.py
- tests/test_metric_libraries.py
Required for https://github.com/mozilla/jetstream/issues/616
> Add support for Firefox for iOS experiments

- src/mozanalysis/bq.py
- src/mozanalysis/experiment.py
- src/mozanalysis/exposure.py
- src/mozanalysis/metrics/__init__.py
- src/mozanalysis/segments/desktop.py
- tests/test_experiment.py
https://github.com/mozilla/jetstream/issues/649
Does this approach seem right?
> Exposure query

- src/mozanalysis/experiment.py
- src/mozanalysis/metrics/__init__.py
- tests/test_experiment.py
Fixes https://github.com/mozilla/jetstream/issues/650
Depends on https://github.com/mozilla/mozanalysis/pull/130
> Exposure as basis for aggregate tables

- src/mozanalysis/experiment.py
Workaround for mozilla/jetstream#689.
> Ignore enrollments with null client_ids

- docs/api/metrics/fenix.rst
- docs/api/metrics/firefox_ios.rst
- src/mozanalysis/metrics/fenix.py
- src/mozanalysis/metrics/firefox_ios.py
This will render pages like https://mozilla.github.io/mozanalysis/api/metrics/desktop.html for the Glean apps.
> Document Glean apps

- docs/api/segments/desktop.rst
- src/mozanalysis/segments/desktop.py
> Add autodocs for segments

- src/mozanalysis/metrics/focus_android.py
- src/mozanalysis/metrics/klar_android.py
- tests/test_experiment.py
- tests/test_metric_libraries.py
Required for https://github.com/mozilla/jetstream/issues/795
> Add support for Klar Android and Android Focus

- src/mozanalysis/experiment.py
- src/mozanalysis/exposure.py
- src/mozanalysis/metrics/__init__.py
- tests/test_experiment.py
WIP for https://github.com/mozilla/mozanalysis/issues/144
> Flexible exposure signal support

- src/mozanalysis/__init__.py
Required for https://github.com/mozilla/jetstream/pull/971
> Specify __all__ for metrics and segments module

- src/mozanalysis/__init__.py
mozanalysis init comment updated to be a little bit more accurate.
> mozanalysis init comment updated

- src/mozanalysis/bayesian_stats/bayesian_bootstrap.py
- src/mozanalysis/frequentist_stats/bootstrap.py
Fixes https://github.com/mozilla/jetstream/issues/1140
> Update conversion of dataframes to numpy arrays

- .circleci/config.yml
> Update SSH Key

- src/mozanalysis/metrics/__init__.py
Going back to pre https://github.com/mozilla/mozanalysis/pull/169 so that we don't unenroll clients during analysis
> Revert changes from #169

- src/mozanalysis/experiment.py
- tests/test_experiment.py
- builds enrollment and exposure queries for Cirrus
- adds an enum for the allowed query types
- adds a test to make sure cirrus queries are built properly
> handle enrollments and exposures queries for cirrus

- src/mozanalysis/experiment.py
> docs: update docstrings for custom_exposure_query and custom_enrollments_query

- docs/adrs/adr-0001-dependency_management.md
Addresses #202 
Evaluates the pros and cons of using pip-tools and poetry for better dependency resolution.
> Added ADR file to evaluate methods for better dependency resolution

- src/mozanalysis/frequentist_stats/linear_models/functions.py
- src/mozanalysis/types.py
- tests/frequentist_stats/test_linear_model_functions.py
Also improves the type checking
> Additional failure cases
