mozilla/mozanalysis

- src/mozanalysis/metrics.py
- tests/test_experiments.py
Per e.g.
https://metrics.mozilla.com/protected/sguha/shield_bootstrap.html,
intensity should be active_hours / total_hours, so that it ends up
generally being a fraction on [0, 1].
> Fix intensity definition

- CHANGELOG.rst
- src/mozanalysis/experiments.py
Spark is smart about unpersisting on its own, and we may want to perform
additional computations on the cached data if we're working
interactively.
> Don't unpersist the dataset

- tox.ini
Touching core Objective C classes from a child process (in the case of
fork() without exec()) causes a defensive crash in recent versions of
macOS.
Pyspark forks unsafely, which triggers the defensive crash, which causes
tests to fail.
This doesn't fix anything -- it just disables the airbag -- but a proper
fix would have to land in pyspark.
Closes #40.
> Work around unsafe fork in pyspark

- .circleci/config.yml
If you stand in one place long enough, the sands shift around you.
The package openjdk-8-jre-headless has been removed from the new debian (buster) and so the easiest short term fix for this is to stay on the old version.
> Keep using debian stretch (oldstable).

- src/mozanalysis/experiment.py
- tests/test_experiment.py
Our next priorities are to introduce a metrics library and support for querying time series of metrics data. Both of these things add complexity to the queries that get sent to Spark, and the code that builds them. Here we lay some groundwork for those features by disentangling some logic from the `Experiment` class.
Here we introduce the `TimeLimits` class: an instance of TimeLimits holds all the temporal information used when querying data for an `Experiment`. It contains the start and end of the enrollment period, the details about the analysis window, and the relevant date range for the data source.
Previously, we tried to hold minimal state and compute quantities on the fly. Instead, `TimeLimits` precomputes and stores all these variables, which is conceptually easier (particularly …
> Refactor time limits code in Experiment.

- src/mozanalysis/experiment.py
- tests/bayesian_stats/test_consistency.py
- tests/test_experiment.py
Do more groundwork in preparation for supporting querying of time series and a metrics library.
Specifically, spin off the construction of the join conditions into a separate method so that `get_per_client_data()` fits on one screen and is easier to reason about.
> Further refactoring of Experiment class

- docs/api/metrics.rst
- docs/api/metrics/desktop.rst
- docs/api/metrics/firetv.rst
- docs/conf.py
- docs/guide.rst
- docs/index.rst
- src/mozanalysis/experiment.py
- src/mozanalysis/metrics/__init__.py
- src/mozanalysis/metrics/desktop.py
- src/mozanalysis/metrics/firetv.py
- tests/test_experiment.py
- tests/test_metric_libraries.py
- tests/test_metrics.py
Warning: this makes a breaking change to the main user-facing functions, and redefines `metric_list`.
Rather than supplying both `data_source: DataFrame` and `metric_list: iterable[Column]` to `Experiment.get_per_client_data()`, `Experiment.get_time_series_data()` and `Experiment.get_time_series_data_lazy()`, now you supply `metric_list: iterable[Metric]` - where `Metric` is a new type that represents a... metric.
In the medium-long term, on most experiments, most `Metric`s will be imported from the metrics library (e.g. `mozanalysis.metrics.desktop` for desktop experiments). The metrics library will be the canonical definition of the various metrics.
It's also fairly easy to define one-off `Metric`s for an experiment. If there's any likelihood of reuse, people should be encouraged to add …
> Start a metrics library

- src/mozanalysis/bayesian_stats/bayesian_bootstrap.py
- src/mozanalysis/frequentist_stats/bootstrap.py
- tests/bayesian_stats/test_bayesian_bootstrap.py
- tests/bayesian_stats/test_consistency.py
- tests/conftest.py
- tests/frequentist_stats/test_bootstrap.py
This makes a breaking change to the bootstrap function signatures: arguments are re-ordered so that `sc` becomes optional.
Mozanalysis will now be frequently run without a Spark context. We'll still need to bootstrap.
Now if no Spark context is supplied, non-parallel implementations of the bootstrap will be run.
>  Make bootstrapping work without Spark.

- src/mozanalysis/metrics/__init__.py
- src/mozanalysis/metrics/desktop.py
In order to add 'connect_fxa' as a metric, I had to un-break the join to the `events` table (the changes in `metrics/__init__.py`).
I applied this quickly to [an existing onboarding experiment](https://colab.research.google.com/drive/1fQQVj7yB3x9NHIRxI371_Pk0VEGxXV9W) and the metric result was nonzero and plausible (to me).
@tdsmith: can you please review the changes to `__init__.py` - it would be particularly appreciated if you can think of a better name than 'map_struct'.
@irrationalagent: could you please check that the metric is defined correctly and named sensibly? My [application notebook](https://colab.research.google.com/drive/1fQQVj7yB3x9NHIRxI371_Pk0VEGxXV9W) has the full generated query, if you want to see how the `Metric` object is used to form a concrete SQL query.
> Add metric for connecting a firefox account

- .circleci/config.yml
- README.md
- tox.ini
Tests started failing on py27, in areas untouched by recent commits. The ship is sinking, let's get off it.
I have little idea what I'm doing w.r.t. packaging, but after making these changes `tox` ran successfully from scratch and I could find no further references to 'py2' or 'python2' in the project, so this seems to have worked?
> Remove py27 support - abandon ship.

- src/mozanalysis/bq.py
- src/mozanalysis/experiment.py
- src/mozanalysis/metrics/__init__.py
All classes inherit from object in Python 3. It's a brave new world!
https://twitter.com/electrolemon/status/1043183150216765440
> Remove explicit object inheritance

- src/mozanalysis/metrics/__init__.py
Sometimes you have tables with identical schemas and need to prefer one or the other in different contexts. These could be using `telemetry_live` tables, or using a Fenix Nightly table vs a Fenix release table. This helper facilitates that.
> Allow Metrics to be rebased on other DataSources

- src/mozanalysis/experiment.py
- tests/test_experiment.py
Rationale: pensieve wants to be opinionated about how it runs queries (e.g. specifying destination table names, maybe not materializing results immediately) in ways that we don't need to expose to interactive users. `get_time_series_data` and `get_single_window_data` are thin wrappers around this function; instantiating a TimeLimits object is something that pensieve can do. Generating this query is how mozanalysis adds value, so let's expose the query directly.
Moots #60.
> Promote build_query to public API

- src/mozanalysis/metrics/desktop.py
Added the following fields to the desktop metrics file:
* `tagged_sap`
* `tagged_follow_on`
* `search_with_ads`
> Add missing search metrics

- src/mozanalysis/segments/desktop.py
Because `clients_last_seen` is constructed from the `main` ping, and our enrollments are obtained from the `events` ping,there are enrollments without a `clients_last_seen` row that matches the submission date.
This only happens for users without any (main ping) activity in the past 28 days. Therefore these users belong in `new_irregular_users_v2`.
This problem will persist even once the segments are in the ETL.
There are terser solutions (e.g. `MAX(...=...) IS TRUE` for two segments to map `NULL` to `FALSE`), but I figured that this verbose form was the most readily understandable.
> COALESCE segments to remove NULL values

- src/mozanalysis/metrics/desktop.py
Adds a datasource pointing to the `messaging_system.cfr` which contains the CFR metrics events.
A couple notes: the `experiments` column on this table was recently fixed, I believe it is of type `simple` (the default for the DataSource class).
I am not adding metrics here, because there are additional variable(s) `bucket_id` and `message_id` that are required to filter down to the CFR campaign of interest (in a CFR experiment, an enrolled user may see multiple CFR campaigns, so its not possible to just pull all rows from the CFR table matching an enrolled client_id).
For example, for a recent experiment my metric definition looked like this:
```python
cfr_impression = Metric(
name='cfr_impression',
data_source=cfr,
select_expr=agg_any("""event = 'IMPRESSION' 
AND bucket_id = {}
AND …
```
> add cfr DataSource

- src/mozanalysis/segments/desktop.py
- tests/test_segment_libraries.py
Docs for these segments are [on DTMO](https://docs.telemetry.mozilla.org/concepts/segments.html#regular-users-v3).
Here's a [colab notebook](https://colab.research.google.com/drive/1C1y3DbZ4vN1-gIh5JrIcQL8c8kZv8WoK) that demonstrates that this generates valid SQL that executes against our DB!
> Update usage regularity segments to v3.

- src/mozanalysis/metrics/desktop.py
In pensieve, calculating the unenroll metric on a daily basis is quite expensive since currently `telemetry.events` is queried directly without any filtering. If we make use of  the `event_category` partitioning running the query only costs us a fraction.
I'm not sure if unenroll results are still correct with these changes though...
> normandy_events datasource for unenroll metric

- src/mozanalysis/metrics/__init__.py
- src/mozanalysis/metrics/desktop.py
- src/mozanalysis/metrics/fenix.py
- tests/test_metric_libraries.py
Follow up to https://github.com/mozilla/jetstream/issues/109.
@emtwo, this will be part of our solution for exposing documentation about metrics to the dashboarding layer eventually; is Markdown an okay format for the extended documentation strings?
> Add friendly names and docs to metrics definitions

- docs/api/metrics/desktop.rst
- src/mozanalysis/metrics/desktop.py
It turns out Sphinx refuses to emit anything for undocumented module constants. But we can add trivial documentation.
If anyone gets bored enough, I think the proper thing to do here is to write a Sphinx extension that hooks the autodoc [process-docstring](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#docstring-preprocessing) event and replaces "..." with the `description` field, though I'm not sure how to reason about the description containing Markdown and the Sphinx docs being more or less in RST -- eh!
> Emit Sphinx docs for desktop metrics

- src/mozanalysis/metrics/__init__.py
- src/mozanalysis/metrics/desktop.py
- src/mozanalysis/metrics/fenix.py
Dashboards shouldn't look excited when we get more of a bad thing, or when performance timings increase.
Sometimes this will depend on the context of the experiment; if the wrong assertion is made here, folks can make a copy of the metric with the bit flipped.
cf https://github.com/mozilla/jetstream/issues/252
> Add a lower-is-better flag

- src/mozanalysis/metrics/desktop.py
@SuYoungHong noticed that the results of the `days_of_use` metric introduced in PR #105 were very suspicious.
The `COUNT(*)` was counting enrollments even when they had no row in `clients_daily`. Oops.
Instead, we need to `COUNT()` a non-null column from `clients_daily`; `COUNT(ds.submission_date)` seems to be the best for communicating what this metric does? And it's not worth adding a `DISTINCT` because it's implied by `clients_daily` and the lack of other joins?
I haven't tried this code yet but I've asked Su to do so in [this notebook](https://colab.research.google.com/drive/1E-f35o3DE6FIdnmNjs7eEA413lkNjtLh).
> Fix the `days_of_use` metric.

- .circleci/config.yml
- setup.py
- tox.ini
- Declare pyarrow and google-cloud-bigquery-storage as dependencies so people get fast .to_dataframe() without extra work
- Build on interesting Python environments: Colab is 3.6 and Jetstream uses 3.8, so test those
> Build hacks

- src/mozanalysis/bq.py
- src/mozanalysis/experiment.py
- tests/test_experiment.py
Repeated references to the enrollments CTE seem to stress BigQuery out, giving rise to "Resources exceeded during query execution: Not enough resources for query planning - too many subqueries or query is too complex." errors.
If we use CREATE TEMPORARY TABLE to materialize the enrollments table before joining it everywhere, we get a scripting query with similar semantics and a calmer query planner.
~Caveat: I just realize this doesn't quite work yet, so leaving this as a draft for now; we can't set a destination-table name at execution time for a scripting query, so we have to replace the SELECT down there with another `CREATE TABLE {destination_table} AS` instead.~
cc @felixlawrence, @scholtzan
> Materialize enrollments table

- src/mozanalysis/metrics/desktop.py
Revise the Pocket tile clicks metrics added in an earlier PR:
https://github.com/mozilla/mozanalysis/pull/102
In particular, make two changes:
-drop the metric for whether a user clicked a Pocket tile at all in favor of only count metrics
-split "Pocket tile clicks" into two buckets: Pocket organic recommendation clicks and Pocket sponsored content clicks
> Revise metrics for Pocket tile clicks.

- src/mozanalysis/metrics/fenix.py
Addresses the issue described in #107, where the join changes the meaning of COUNT(*).
> Fix ping count metrics

- src/mozanalysis/experiment.py
- src/mozanalysis/metrics/__init__.py
- src/mozanalysis/metrics/fenix.py
- src/mozanalysis/segments/__init__.py
- tests/test_experiment.py
- tests/test_metric_libraries.py
- tests/test_metrics.py
- tests/test_segment_libraries.py
Different release channels of Glean apps have their data stored in different BigQuery datasets. This departs from the legacy telemetry practice on desktop, where data from all release channels end up in a single table.
This means that, although it's reasonable to talk about a set of metrics that are valid across the different Fenix release channels, the underlying DataSources need to be customized for each release channel.
I had once expected that this would be easy to do just by defining an alternate set of DataSources and rebasing the Metrics onto the new DataSources -- but the `events` data source is a good example of why this isn't as easy as I'd like. Data sources can be complex and it would be annoying to redefine them.
Instead, allow DataSources to be templated over dataset, and …
> Make metric datasets configurable at runtime

- src/mozanalysis/segments/desktop.py
Use clients_first_seen to identify profiles that enroll on their first date of use.
> Add a new-profile segment

- src/mozanalysis/bq.py
- src/mozanalysis/experiment.py
- src/mozanalysis/metrics/__init__.py
- src/mozanalysis/segments/__init__.py
When I went to test in [a notebook](https://colab.research.google.com/drive/1x9wBQc7h80zpmymH-gs7seoP2Opxd-QG) the original change that fixes #117 and an equivalent bug with segments (commit 56d97bd), I found a bunch of apparently-broken functionality that led me on a merry end-of-year yak shave. Thanks @tdsmith for coming along for the ride!
In [the notebook](https://colab.research.google.com/drive/1x9wBQc7h80zpmymH-gs7seoP2Opxd-QG) I tested both `Experiment.get_time_series_data()` and `Experiment.get_single_window_data()`, and the results indicate that the bug is fixed (max 7 days of use in a week) and the methods both work and yield consistent results.
We should consider making the result _formats_ more consistent (hiding client_id and analysis window details from …
> Join enrollments more rigorously... and fix what was broken

- src/mozanalysis/metrics/desktop.py
The telemetry to properly calculate the number of users un-ticking the options to show Pocket and/or Pocket sponsored stories in New Tab was added to FX86 🎉
> Add metrics for disabling Pocket in New Tab.

- .circleci/config.yml
- README.md
- docs/api/segments/desktop.rst
Fixes https://github.com/mozilla/mozanalysis/issues/121
The repo branch has already been set to `main`, but `master` is referenced in a couple of places
> Rename master -> main

- src/mozanalysis/metrics/desktop.py
Uses the `telemetry_stable.main_v4` table instead of the `telemetry.main` compatibility view for the `main` data source.
This is intended to reduce the complexity of the analysis query in order to stay within Google's complexity budget.
We expect that this is compatible with all existing metrics because the view doesn't make very many changes, although the changes it does make are fairly complex.
> Use concrete table for main data source

- docs/guide.rst
- setup.py
- src/mozanalysis/__init__.py
- src/mozanalysis/bayesian_stats/bayesian_bootstrap.py
- src/mozanalysis/bq.py
- src/mozanalysis/config.py
- src/mozanalysis/experiment.py
- src/mozanalysis/frequentist_stats/bootstrap.py
- src/mozanalysis/metrics/__init__.py
- src/mozanalysis/metrics/desktop.py
- src/mozanalysis/metrics/fenix.py
- src/mozanalysis/metrics/firefox_ios.py
- src/mozanalysis/metrics/focus_android.py
- src/mozanalysis/metrics/focus_ios.py
- src/mozanalysis/metrics/klar_android.py
- src/mozanalysis/metrics/klar_ios.py
- src/mozanalysis/segments/desktop.py
- tests/test_experiment.py
- tests/test_segment_libraries.py
- tox.ini
With this change mozanalysis will use the new [jetstream-config-parser](https://github.com/mozilla/jetstream-config-parser) to pull in configurations from jetstream-config. The changes introduced here shouldn't break any existing code.
I've already migrated existing metric, data source and segment definitions to https://github.com/mozilla/jetstream-config/tree/main/definitions, but it would probably be best to validate them.
> Pull in configurations from jetstream-config

- src/mozanalysis/experiment.py
I am guessing that at some point we switched from `exposure` to `expose` as the `event_method` (or maybe were just leaving open both possibilities) and that this was meant to be `OR` to account for either option.
> fix typo in exposures query

- src/mozanalysis/frequentist_stats/sample_size.py
- tests/frequentist_stats/test_sample_size_calc.py
Updates naming convention for results DataFrames for experiment sizing to denote sizes are per branch in the study.
> Clarifies sample size results as per branch

- src/mozanalysis/frequentist_stats/sample_size.py
- src/mozanalysis/sizing.py
- src/mozanalysis/utils.py
- tests/conftest.py
- tests/test_sizing.py
- Renames the results for sample size calc to make explicit that sizes are per branch of a study.
- Fixes joins for creating targets to use INNER rather than LEFT joins.
> Mbowerman sizing results rename

- src/mozanalysis/sizing.py
Before, metrics collection for analysis began on the day of enrollment of a client for sample size calculation. This shifts the window to collect to 1 day after enrollment.
> Move sizing analysis window

- src/mozanalysis/metrics/__init__.py
This was causing `Syntax error: Expected keyword JOIN but got ")"`
> Remove parens in metric query

- src/mozanalysis/metrics/__init__.py
Adds a condition that returns from the `from_expr_for` method when no experiment slug is passed, as is always the case when constructing queries for experiment sizing.
> Fix #180: bug in sizing metrics query construction

- src/mozanalysis/frequentist_stats/bootstrap.py
- src/mozanalysis/utils.py
- tests/frequentist_stats/test_bootstrap.py
- tests/test_utils.py
For the Google Trending experiment, we need this metric:
`ad click rate = (sum of ad clicks over all clients) / (sum of SAPs over all clients)`
This is a PR to allow Mozanalysis (and eventually Jetstream) to compute this metric.
I suggest this change because truncating outliers doesn't make sense when your metric involves multiple columns in a dataframe. For example, if we truncate outliers, then we have to answer questions like:
- if a client has an outlier value for searches, but not ad clicks, should we keep it?
- if a client has an outlier value for ad clicks, but not searches, should we keep it?
Capping avoids these problems (we keep all clients) and has been shown to have good theoretical properties when used with a mean: see[ Lugosi & Mendelson](https://arxiv.org/abs/1906.04280). …
> Ad click rate

- src/mozanalysis/bayesian_stats/bayesian_bootstrap.py
The vast majority of the current time is in:
np.random.RandomState(unique_seed)
Previously, when generation of the sample weights was parallelized it made sense to reseed for each sampling so that it was deterministic. However, that parallelization was removed in e33914d7fa42bfa1f305d14ee7b96c3a39643abb
With that gone we can drop the reseeding entirely which makes 16 or so 100 sample calls to compare_branches go from 50seconds down to 5.
> Improve the performance of bayesian bootstrap by 10x

- src/mozanalysis/experiment.py
- tests/test_experiment.py
Adds a `sample_size` parameter to the functions building enrollments queries. This will allow us to update metric-hub configs to support easier downsampling without having to redefine the entire enrollments query. From the config, jetstream can retrieve this sample size and pass it into mozanalysis when building the enrollments query.
> fix #187: add sample_size param to enrollments query functions

- src/mozanalysis/experiment.py
- tests/test_experiment.py
The unset `None` value was be propagated down into the query, causing an issue when the query tried to run `sample_id < None`.
I also noticed that I had `sample_id <=` instead of `<` in the queries, which could be confusing (`sample_size` of `10` would actually be an `11%` sample with `<=`), so I fixed that.
> fix #189: explicitly set sample_size to 100 if unset or None

- src/mozanalysis/experiment.py
Glean enrollments query uses `UNNEST(events.events)` as `e` instead of just `events` so we need to change the WHERE clause to remove the `e.` from `sample_id`.
> fix glean enrollments query with sample_id

- src/mozanalysis/experiment.py
`2023.10.1` introduced a parameter for filtering on a passed category instead of a static string, but was missing quotes around the value. This PR fixes that.
> fix category filter: add quotes to value

- src/mozanalysis/frequentist_stats/bootstrap.py
- tests/frequentist_stats/test_bootstrap.py
This PR provides a new method for quantile inference using a "resampling-free bootstrap". It [provides](https://colab.research.google.com/drive/1WVtx7w9zWSYx5MQTZxQo4gWz73-KlWY0#scrollTo=CWfq0kZYuu5d) >100x speedups over the current implementation (comparison tests in the linked notebook). 
This is valuable as, in some cases, the vast majority of Jetstream analysis duration is spent in the decile statistic.
> Faster decile inference

- src/mozanalysis/frequentist_stats/bootstrap.py
- tests/frequentist_stats/test_bootstrap.py
To fix the errors like `Error while computing statistic deciles for metric default_browser_card_go_to_settings_pressed: index 30 is out of bounds for axis 0 with size 30`
> Fix get_quantile_bootstrap_samples index errors

- docs/api/config.rst
- docs/guide.rst
- src/mozanalysis/config.py
- tests/test_config.py
This will be useful when we want to use metrics or data sources defined in metric-hub outcomes in sizing or other ad-hoc calculations. The current workflow is to copy-paste the metric definition. `ConfigLoader` is now the main way that metric-hub configs are accessed by data scientists working in notebooks.
Other updates:
- Add tests for config.py
* Currently this relies on pulling specific configs from metric-hub, which could change in the future. The "proper" way would be to mock a version of metric-hub in this repo, but I wasn't sure that was necessary at this point.
- Add API docs for config.py
- Minor cleanup of markup in guide doc page
- Fix setting description for metrics
> Add loading for metrics & data sources defined in outcomes

- src/mozanalysis/frequentist_stats/sample_size.py
- tests/frequentist_stats/test_sample_size_calc.py
This adds metric mean value and relative effect size to the empirical sizing output dict.
Additionally:
- Simplify the code to build the result dict
- Add a test for empirical sizing
> Expand empirical effect size results

- src/mozanalysis/__init__.py
This is meant to address this issue: https://github.com/mozilla/mozanalysis/issues/11
One can access the version using the __version__ attribute:
```
>>> import mozanalysis
>>> mozanalysis.__version__
'2023.11.4.dev12+g230bf07.d20240227'
```
It looks like the version is generated by `setuptools_scm`, and it gets grabbed by `importlib.metadata`.  We could add a little logic just to grab the date part of it so it matches with the git tags.
> feat: add __version__ attribute

- src/mozanalysis/config.py
- src/mozanalysis/metrics/__init__.py
- src/mozanalysis/segments/__init__.py
- src/mozanalysis/sizing.py
- tests/test_sizing.py
Fixes #173 
- Add `app_name` attribute to Metric, Segement, etc classes so that sources from metric-hub can be checked
- exceptions raised for metric_list with multiple sources, target_list with multiple sources and when the sources between the two don't match
- Add warning for causes where there are metrics or segements not from metric-hub, and a metric has all 0s (which would indicate no support for the metric and therefore a mismatch between target and metric sources)
> Verify target_list and metric_list sources match

- setup.py
- src/mozanalysis/frequentist_stats/sample_size.py
- tests/frequentist_stats/test_sample_size_calc.py
This PR is adding wrapper classes for results returned from the objects in sample_size_calc.py.  The idea is to add functionality to make it easier to work with results while maintaining backward compatibility
Fixes #204
> Improve readability of sizing functions

- README.md
- tests/frequentist_stats/test_linear_model_functions.py
Was playing around with the tests for something else and noticed that we were checking for `Exception` when we could be more specific. Also saw some extremely minor typos in the README that I fixed for consistency.
> chore: more precise errors in tests; README typos

- src/mozanalysis/experiment.py
- tests/test_experiment.py
As per [this comment](https://mozilla-hub.atlassian.net/browse/DS-3857?focusedCommentId=924733), the decision which enables sampling by profile group ID has been approved. This PR removes the restriction preventing downsampling for group level experiments.
> Remove downsampling restriction for group level experiments

- src/mozanalysis/experiment.py
- src/mozanalysis/exposure.py
- src/mozanalysis/metrics.py
- src/mozanalysis/segments.py
- tests/test_metrics.py
- exposure signal build_query updates needed to support profile_group_id
- re-checked the prior changes and made some updates for consistency (e.g., `analysis_id` instead of `id_column` in metrics.py)
- also looked like the segments query was slightly wrong
- some minor comment updates to reflect the generic usage of analysis unit vs specifically client_id
> add analysis unit to exposure signal; consistent id usage in query builders

- src/mozanalysis/experiment.py
- src/mozanalysis/exposure.py
- src/mozanalysis/metrics.py
- src/mozanalysis/segments.py
- tests/test_experiment.py
- tests/test_metrics.py
Before this change, the analysis tables would have an inconsistent identifier column called either `client_id` or `profile_group_id`, depending on the experiment. This change renames that column to `analysis_id` for all experiments.
> use analysis_id instead of client/profile_group for consistency

- src/mozanalysis/experiment.py
- tests/test_experiment.py
Updated some more comments about custom queries to reflect the change in queries from client_id to analysis_id.
> add warning if wrong analysis_unit in custom query

- .circleci/config.yml
Updates node base image and gh-pages dep to latest because
- node version 8.10.0 is 7 years old
- gh-pages version 2.0.1 is 6 years old
> chore: update docs-deploy to supported dep versions

- src/mozanalysis/experiment.py
Changes the experiment enrollment query for Glean experiments to query `events_stream` instead of `events`. This should be a more efficient query.
> Query events_stream table for Glean experiment enrollment

- src/mozanalysis/frequentist_stats/sample_size.py
- tests/bayesian_stats/test_bayesian_bootstrap.py
- tests/bayesian_stats/test_survival_func.py
- tests/frequentist_stats/test_bootstrap.py
- tests/frequentist_stats/test_linear_model_functions.py
- tests/test_sizing.py
Noticed there were a handful of warnings coming out of running pytest due to some deprecated calls, or in some cases expected behavior that we weren't accounting for in the tests (e.g., UserWarnings that we expect to raise, or side effects of our use of 0'd out dataframes for tests).
> chore: fix warnings raised by tests

- src/mozanalysis/experiment.py
- tests/test_experiment.py
Because we have updated from user_id to nimbus_user_id https://github.com/mozilla/experimenter/pull/12017/files ,  so updating to reflect the same here
> feat(nimbus): Update to nimbus user id

- src/mozanalysis/metrics.py
I don't know if this is correct, but when I added `experiments_column_type == "events_stream"`, I saw that the first metric doesn't use f-string and the second metric does, even though both reference experiment_slug.
> fix: sanity metric query strings should be f-strings
